<?php
/**
 * BehaviorsArgument
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BehaviorsArgument Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BehaviorsArgument implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Behaviors_argument';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'type' => 'string',
        'limit_by' => 'string',
        'average_rate_limit' => 'int',
        'maximum_burst_size' => 'int',
        'waf_id' => 'int',
        'mode' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'type' => null,
        'limit_by' => null,
        'average_rate_limit' => null,
        'maximum_burst_size' => null,
        'waf_id' => null,
        'mode' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
		'type' => false,
		'limit_by' => false,
		'average_rate_limit' => false,
		'maximum_burst_size' => false,
		'waf_id' => false,
		'mode' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'type' => 'type',
        'limit_by' => 'limit_by',
        'average_rate_limit' => 'average_rate_limit',
        'maximum_burst_size' => 'maximum_burst_size',
        'waf_id' => 'waf_id',
        'mode' => 'mode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'type' => 'setType',
        'limit_by' => 'setLimitBy',
        'average_rate_limit' => 'setAverageRateLimit',
        'maximum_burst_size' => 'setMaximumBurstSize',
        'waf_id' => 'setWafId',
        'mode' => 'setMode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'type' => 'getType',
        'limit_by' => 'getLimitBy',
        'average_rate_limit' => 'getAverageRateLimit',
        'maximum_burst_size' => 'getMaximumBurstSize',
        'waf_id' => 'getWafId',
        'mode' => 'getMode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_SECOND = 'second';
    public const TYPE_MINUTE = 'minute';
    public const LIMIT_BY_CLIENT_IP = 'client_ip';
    public const LIMIT_BY__GLOBAL = 'global';
    public const MODE_LEARNING = 'Learning';
    public const MODE_BLOCKING = 'Blocking';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_SECOND,
            self::TYPE_MINUTE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLimitByAllowableValues()
    {
        return [
            self::LIMIT_BY_CLIENT_IP,
            self::LIMIT_BY__GLOBAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModeAllowableValues()
    {
        return [
            self::MODE_LEARNING,
            self::MODE_BLOCKING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('limit_by', $data ?? [], null);
        $this->setIfExists('average_rate_limit', $data ?? [], null);
        $this->setIfExists('maximum_burst_size', $data ?? [], null);
        $this->setIfExists('waf_id', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLimitByAllowableValues();
        if (!is_null($this->container['limit_by']) && !in_array($this->container['limit_by'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'limit_by', must be one of '%s'",
                $this->container['limit_by'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['average_rate_limit']) && ($this->container['average_rate_limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'average_rate_limit', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['maximum_burst_size']) && ($this->container['maximum_burst_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'maximum_burst_size', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['waf_id']) && ($this->container['waf_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'waf_id', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets limit_by
     *
     * @return string|null
     */
    public function getLimitBy()
    {
        return $this->container['limit_by'];
    }

    /**
     * Sets limit_by
     *
     * @param string|null $limit_by limit_by
     *
     * @return self
     */
    public function setLimitBy($limit_by)
    {
        if (is_null($limit_by)) {
            throw new \InvalidArgumentException('non-nullable limit_by cannot be null');
        }
        $allowedValues = $this->getLimitByAllowableValues();
        if (!in_array($limit_by, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'limit_by', must be one of '%s'",
                    $limit_by,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['limit_by'] = $limit_by;

        return $this;
    }

    /**
     * Gets average_rate_limit
     *
     * @return int|null
     */
    public function getAverageRateLimit()
    {
        return $this->container['average_rate_limit'];
    }

    /**
     * Sets average_rate_limit
     *
     * @param int|null $average_rate_limit average_rate_limit
     *
     * @return self
     */
    public function setAverageRateLimit($average_rate_limit)
    {
        if (is_null($average_rate_limit)) {
            throw new \InvalidArgumentException('non-nullable average_rate_limit cannot be null');
        }

        if (($average_rate_limit < 1)) {
            throw new \InvalidArgumentException('invalid value for $average_rate_limit when calling BehaviorsArgument., must be bigger than or equal to 1.');
        }

        $this->container['average_rate_limit'] = $average_rate_limit;

        return $this;
    }

    /**
     * Gets maximum_burst_size
     *
     * @return int|null
     */
    public function getMaximumBurstSize()
    {
        return $this->container['maximum_burst_size'];
    }

    /**
     * Sets maximum_burst_size
     *
     * @param int|null $maximum_burst_size maximum_burst_size
     *
     * @return self
     */
    public function setMaximumBurstSize($maximum_burst_size)
    {
        if (is_null($maximum_burst_size)) {
            throw new \InvalidArgumentException('non-nullable maximum_burst_size cannot be null');
        }

        if (($maximum_burst_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $maximum_burst_size when calling BehaviorsArgument., must be bigger than or equal to 1.');
        }

        $this->container['maximum_burst_size'] = $maximum_burst_size;

        return $this;
    }

    /**
     * Gets waf_id
     *
     * @return int|null
     */
    public function getWafId()
    {
        return $this->container['waf_id'];
    }

    /**
     * Sets waf_id
     *
     * @param int|null $waf_id waf_id
     *
     * @return self
     */
    public function setWafId($waf_id)
    {
        if (is_null($waf_id)) {
            throw new \InvalidArgumentException('non-nullable waf_id cannot be null');
        }

        if (($waf_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $waf_id when calling BehaviorsArgument., must be bigger than or equal to 1.');
        }

        $this->container['waf_id'] = $waf_id;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


